/** Motion durations are presentation-only. A moving lap is still 1800ms. */
export const FEEL = {
  ORBIT_DURATION: 1800,
  LAUNCH_DURATION: 240,
  ANTICIPATION_DURATION: 20,
  ENERGY_TRAVEL_DURATION: 80,
  IMPACT_DURATION: 10,
  PIXEL_CLEAR_INTERVAL: 110,
  PIXEL_POP_DURATION: 100,
  HOLDING_TRAVEL_DURATION: 300,
  BURST_DURATION: 180,
  WIN_DELAY: 200,
  FAIL_DELAY: 160,
} as const;
