import React from 'react';
import { View, Text } from './react-native';
const sv = (v: any) => ({ value: v, set(n: any) { this.value = typeof n === 'function' ? n : n; }, get() { return this.value; } });
export const useSharedValue = (v: any) => React.useRef(sv(v)).current as any;
export const useDerivedValue = (f: any) => { const r = React.useRef(sv(undefined)).current as any; r.value = f(); return r; };
export const useAnimatedStyle = (f: any) => f();
export const useAnimatedReaction = () => {};
export const useAnimatedProps = (f: any) => f();
export const useReducedMotion = () => false;
export const withTiming = (v: any) => v;
export const withSpring = (v: any) => v;
export const withDelay = (_d: any, v: any) => v;
export const withSequence = (...v: any[]) => v[v.length - 1];
export const withRepeat = (v: any) => v;
export const cancelAnimation = () => {};
export const runOnJS = (f: any) => f;
export const runOnUI = (f: any) => f;
export const interpolate = (x: number) => x;
export const interpolateColor = () => '#ffffff';
export const Easing = { linear: (x: number) => x, out: (f: any) => f, in: (f: any) => f, inOut: (f: any) => f, quad: (x: number) => x, cubic: (x: number) => x, bezier: () => (x: number) => x };
const A: any = (p: any) => React.createElement('AnimatedView', p, p.children);
A.View = View; A.Text = Text;
A.createAnimatedComponent = (c: any) => c;
export default A;
// Layout-animation builders (FadeIn.duration(120).springify()...) — chainable no-ops.
const builder: any = new Proxy(function () {}, { get: (_t, k) => (k === 'build' ? () => ({}) : () => builder), apply: () => builder });
export const FadeIn = builder; export const FadeOut = builder; export const ZoomIn = builder; export const ZoomOut = builder;
export const FadeInDown = builder; export const FadeInUp = builder; export const FadeOutDown = builder; export const SlideInDown = builder;
export const LinearTransition = builder;
export const measure = () => null;
export const useAnimatedRef = () => React.useRef(null);
export const makeMutable = (v: any) => sv(v);
export const ReduceMotion = { System: 0, Always: 1, Never: 2 };
