import type { LevelDefinition } from '../engine/types';

/** Handcrafted M1 campaign for shared insertion, dynamic encounters and manual Holding. */
export const LEVEL_DEFINITIONS: LevelDefinition[] = [
  {
    id: 1, title: 'Moon', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '.WWWWW.',
      'WW.....',
      'WW.....',
      'WW.....',
      'WW.....',
      'WW.....',
      '.WWWWW.',
    ],
    tunnels: [
      [{ color: 'white', capacity: 7 }],
      [{ color: 'white', capacity: 7 }],
      [{ color: 'white', capacity: 6 }],
    ],
  },
  {
    id: 2, title: 'Star', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '...W...',
      '.W.W.W.',
      '..WWW..',
      'WWWYWWW',
      '..WWW..',
      '.W.W.W.',
      '...W...',
    ],
    tunnels: [
      [{ color: 'white', capacity: 7 }, { color: 'yellow', capacity: 1 }],
      [{ color: 'white', capacity: 7 }],
      [{ color: 'white', capacity: 6 }],
    ],
  },
  {
    id: 3, title: 'Small Planet', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '...C...',
      '..CCC..',
      '.CCCCC.',
      'CCCWCCC',
      '.CCCCC.',
      '..CCC..',
      '...C...',
    ],
    tunnels: [
      [{ color: 'cyan', capacity: 1 }, { color: 'white', capacity: 1 }, { color: 'cyan', capacity: 7 }],
      [{ color: 'cyan', capacity: 10 }],
      [{ color: 'cyan', capacity: 6 }],
    ],
  },
  {
    id: 4, title: 'Rocket', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '...R...',
      '..RRR..',
      '..RRR..',
      '..WWW..',
      '..WBW..',
      '..WBW..',
      '.WWWWW.',
      '.O.O.O.',
      '...O...',
    ],
    tunnels: [
      [{ color: 'blue', capacity: 2 }, { color: 'white', capacity: 12 }],
      [{ color: 'red', capacity: 7 }],
      [{ color: 'orange', capacity: 4 }],
    ],
  },
  {
    id: 5, title: 'Comet', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '....WWWW',
      '...WCCCW',
      '...WCWCW',
      '...WCCCW',
      '...WWWWW',
      '..KPP...',
      '.KKP....',
      'KKP.....',
    ],
    tunnels: [
      [{ color: 'white', capacity: 16 }, { color: 'cyan', capacity: 2 }],
      [{ color: 'cyan', capacity: 2 }, { color: 'cyan', capacity: 2 }, { color: 'pink', capacity: 5 }],
      [{ color: 'purple', capacity: 4 }, { color: 'cyan', capacity: 2 }],
    ],
  },
  {
    id: 6, title: 'Ringed Planet', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '..PPP..',
      '.PBBBP.',
      'PPBBBPP',
      'COCCCOC',
      'PPBKBPP',
      '.PBBBP.',
      '..PPP..',
    ],
    tunnels: [
      [{ color: 'blue', capacity: 4 }, { color: 'cyan', capacity: 5 }, { color: 'purple', capacity: 10 }],
      [{ color: 'blue', capacity: 4 }, { color: 'pink', capacity: 1 }, { color: 'purple', capacity: 8 }],
      [{ color: 'blue', capacity: 3 }, { color: 'orange', capacity: 2 }],
    ],
  },
  {
    id: 7, title: 'Satellite', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '..BBB..',
      '.BKKKB.',
      'BKWWWKB',
      'BKWBWKB',
      'BKWWWKB',
      '.BKKKB.',
      '..BBB..',
    ],
    tunnels: [
      [{ color: 'pink', capacity: 4 }, { color: 'white', capacity: 4 }, { color: 'blue', capacity: 16 }, { color: 'blue', capacity: 1 }],
      [{ color: 'pink', capacity: 4 }, { color: 'white', capacity: 4 }],
      [{ color: 'pink', capacity: 4 }],
    ],
  },
  {
    id: 8, title: 'Nebula', themeId: 'first-light',
    difficulty: 'easy', holdingCapacity: 3,
    pixelArt: [
      '..CCC..',
      '.CPPPC.',
      'CPKGKPC',
      'CPGYGPC',
      'CPKGKPC',
      '.CPPPC.',
      '..CCC..',
    ],
    tunnels: [
      [{ color: 'purple', capacity: 4 }, { color: 'pink', capacity: 2 }, { color: 'cyan', capacity: 16 }],
      [{ color: 'green', capacity: 4 }, { color: 'purple', capacity: 4 }],
      [{ color: 'yellow', capacity: 1 }, { color: 'pink', capacity: 2 }, { color: 'purple', capacity: 4 }],
    ],
  },
  {
    id: 9, title: 'Constellation', themeId: 'first-light',
    difficulty: 'medium', holdingCapacity: 3,
    pixelArt: [
      'G.B.B.C',
      '.BBBBB.',
      '.BWWWB.',
      '.BWKWB.',
      '.BWWWB.',
      '.BBBBB.',
      'O.B.B.P',
    ],
    tunnels: [
      [{ color: 'white', capacity: 4 }, { color: 'pink', capacity: 1 }, { color: 'blue', capacity: 20 }, { color: 'green', capacity: 1 }],
      [{ color: 'white', capacity: 2 }, { color: 'white', capacity: 2 }, { color: 'cyan', capacity: 1 }],
      [{ color: 'orange', capacity: 1 }, { color: 'purple', capacity: 1 }],
    ],
  },
  {
    id: 10, title: 'Eclipse', themeId: 'first-light',
    difficulty: 'hard', holdingCapacity: 3,
    pixelArt: [
      '.YYYY.',
      'YWWWWY',
      'OWKKWO',
      'YWKYWY',
      'YWWWWY',
      '.YYYY.',
    ],
    tunnels: [
      [{ color: 'pink', capacity: 1 }, { color: 'white', capacity: 5 }, { color: 'yellow', capacity: 15 }],
      [{ color: 'pink', capacity: 1 }, { color: 'white', capacity: 4 }],
      [{ color: 'pink', capacity: 1 }, { color: 'white', capacity: 3 }, { color: 'orange', capacity: 2 }],
    ],
  },
];
