import type { LevelDefinition } from '../engine/types';
import { makeM4CLevel as level } from './m4cLevelFactory';

export const M4C_WORLD_7: LevelDefinition[] = [
  level({ id: 61, title: 'Paper Glider', themeId: 'skybound', difficulty: 'medium',
    art: ['..CCWCC..','.CCWWWCC.','WWWWYWWWW','CCCYYYCCC','.BBBYBBB.','..RRARR..','...RRR...'],
    queues: [['red','blue'],['cyan','yellow'],['gold','white']] }),
  level({ id: 62, title: 'Sunrise Balloon', themeId: 'skybound', difficulty: 'medium',
    art: ['...AAA...','..AYYYA..','.AORRROA.','AORKKKROA','AOPPPPOAA','.ABBBBBA.','..ACCCA..','...NNN...','...N.N...'],
    queues: [['indigo','cyan','blue'],['purple','pink','red'],['orange','yellow','gold']] }),
  level({ id: 63, title: 'Cloud Windsock', themeId: 'skybound', difficulty: 'medium',
    art: ['WWWWWW...','WCCCCWW..','..RRRROO.','..RRRROOO','..YYYYAAA','..YYYYAA.','..BBBBB..','..B......','..B......'],
    queues: [['blue','yellow'],['red','orange'],['gold','cyan','white']] }),
  level({ id: 64, title: 'Brass Biplane', themeId: 'skybound', difficulty: 'medium',
    art: ['..AAAAA...','..AWWWA...','AAAAAAAAA.','RRRAOARRRR','..AOOOA...','.BBBBBBB..','...B.B....','...G.G....'],
    queues: [['green','blue'],['red','orange'],['white','gold']] }),
  level({ id: 65, title: 'Coral Parachute', themeId: 'skybound', difficulty: 'medium',
    art: ['..DDDDD..','.DRRRRRD.','DROOOOORD','DRYYYYYRD','.DWWWWWD.','..D.D.D..','..C.C.C..','...CCC...','...BBB...'],
    queues: [['blue','cyan'],['white','yellow'],['orange','red','coral']] }),
  level({ id: 66, title: 'Kite Squadron', themeId: 'skybound', difficulty: 'medium',
    art: ['Y.W.K.W.C','.Y.KKK.C.','..YYKCC..','..WWW.WWW','.RRRWWWBBB','.RRR.BBB.','..R...B..','..GG.GG..','..GG.GG..'],
    queues: [['green','red'],['blue','cyan'],['white','pink','yellow']] }),
  level({ id: 67, title: 'Radar Spire', themeId: 'skybound', difficulty: 'medium',
    art: ['....L....','..LLGLL..','.LGTTTGL.','LGTCCC TGL'.replace(' ',''),'.LGTTTGL.','..LLGLL..','...NNN...','...NNN...','..BBBBB..'],
    queues: [['blue','indigo'],['cyan','teal'],['green','lime']] }),
  level({ id: 68, title: 'Rescue Helicopter', themeId: 'skybound', difficulty: 'medium',
    art: ['..WWWWWW.','.....W...','.RRRRRRR.','RRROOOBBR','RRYOOOBBR','.RRRRRRR.','..AAA....','..AAA....','...G.....'],
    queues: [['green','gold'],['yellow','orange'],['blue','red','white']] }),
  level({ id: 69, title: 'Midnight Jetliner', themeId: 'skybound', difficulty: 'hard',
    art: ['..NNNNN...','...NNN....','...NWN....','BBBBBBBBBB','BBCCCCCCBB','..BYYYYB..','...RRRR...','...AAAA...'],
    queues: [['gold','red'],['yellow','cyan'],['white','indigo','blue']] }),
  level({ id: 70, title: 'The Skybound Airship', themeId: 'skybound', difficulty: 'hard',
    art: ['...AAAA...','..AYYYYA..','.AYWWWWYA.','AYWCCCCWYA','AYWBBBBWYA','.AYNNNNYA.','..ARRRRA..','...OOO....','..OGGGO...','...G.G....'],
    queues: [['green','orange','red'],['indigo','blue','cyan'],['white','yellow','gold']] }),
];
