import type { LevelDefinition } from '../engine/types';
import { combineModifiers, frozen, makeM4CLevel as level, shielded } from './m4cLevelFactory';

export const M4C_WORLD_7: LevelDefinition[] = [
  level({ id: 61, title: 'Paper Glider', themeId: 'skybound', difficulty: 'medium',
    art: ['..CCWCC..','.CCWWWCC.','WWWWYWWWW','CCCYYYCCC','.BBBYBBB.','..RRARR..','...RRR...'],
    queues: [['red','blue'],['cyan','yellow'],['gold','white']],
    modifiers: combineModifiers(frozen(['4,0']), shielded(['4,3'])) }),
  level({ id: 62, title: 'Sunrise Balloon', themeId: 'skybound', difficulty: 'medium',
    art: ['...AAA...','..AYYYA..','.AORRROA.','AORKKKROA','AOPPPPOAA','.ABBBBBA.','..ACCCA..','...NNN...','...N.N...'],
    queues: [['indigo','cyan','blue'],['purple','pink','red'],['gold','yellow','orange']],
    modifiers: combineModifiers(frozen(['4,2']), shielded(['4,5'])) }),
  level({ id: 63, title: 'Cloud Windsock', themeId: 'skybound', difficulty: 'medium',
    art: ['WWWWWW...','WCCCCWW..','..RRRROO.','..RRRROOO','..YYYYAAA','..YYYYAA.','..BBBBB..','..B......','..B......'],
    queues: [['blue','yellow'],['red','orange'],['gold','cyan','white']],
    modifiers: combineModifiers(frozen(['2,2']), shielded(['6,4'])) }),
  level({ id: 64, title: 'Brass Biplane', themeId: 'skybound', difficulty: 'medium',
    art: ['..AAAAA...','..AWWWA...','AAAAAAAAA.','RRRAOARRRR','..AOOOA...','.BBBBBBB..','...B.B....','...G.G....'],
    queues: [['green','blue'],['red','orange'],['white','gold']],
    modifiers: combineModifiers(frozen(['3,1']), shielded(['4,3'])) }),
  level({ id: 65, title: 'Coral Parachute', themeId: 'skybound', difficulty: 'medium',
    art: ['..DDDDD..','.DRRRRRD.','DROOOOORD','DRYYYYYRD','.DWWWWWD.','..D.D.D..','..C.C.C..','...CCC...','...BBB...'],
    queues: [['blue','cyan'],['white','yellow'],['coral','red','orange']],
    modifiers: combineModifiers(frozen(['4,4']), shielded(['3,7'])) }),
  level({ id: 66, title: 'Kite Squadron', themeId: 'skybound', difficulty: 'medium',
    art: ['Y.W.K.W.C','.Y.KKK.C.','..YYKCC..','..WWW.WWW','.RRRWWWBBB','.RRR.BBB.','..R...B..','..GG.GG..','..GG.GG..'],
    queues: [['green','red'],['blue','cyan'],['white','pink','yellow']],
    modifiers: combineModifiers(frozen(['4,2']), shielded(['4,4'])) }),
  level({ id: 67, title: 'Radar Spire', themeId: 'skybound', difficulty: 'medium',
    art: ['....L....','..LLGLL..','.LGTTTGL.','LGTCCC TGL'.replace(' ',''),'.LGTTTGL.','..LLGLL..','...NNN...','...NNN...','..BBBBB..'],
    queues: [['blue','indigo'],['teal','cyan'],['lime','green']],
    modifiers: combineModifiers(frozen(['4,3']), shielded(['4,6'])) }),
  level({ id: 68, title: 'Rescue Helicopter', themeId: 'skybound', difficulty: 'medium',
    art: ['..WWWWWW.','.....W...','.RRRRRRR.','RRROOOBBR','RRYOOOBBR','.RRRRRRR.','..AAA....','..AAA....','...G.....'],
    queues: [['green','gold'],['yellow','orange'],['blue','red','white']],
    modifiers: combineModifiers(frozen(['4,3']), shielded(['5,4'])) }),
  level({ id: 69, title: 'Midnight Jetliner', themeId: 'skybound', difficulty: 'hard',
    art: ['..NNNNN...','...NNN....','...NWN....','BBBBBBBBBB','BBCCCCCCBB','..BYYYYB..','...RRRR...','...AAAA...'],
    queues: [['gold','red'],['cyan','yellow'],['white','indigo','blue']],
    modifiers: combineModifiers(frozen(['4,2','3,1']), shielded(['4,5','5,3'])) }),
  level({ id: 70, title: 'The Skybound Airship', themeId: 'skybound', difficulty: 'hard',
    art: ['...AAAA...','..AYYYYA..','.AYWWWWYA.','AYWCCCCWYA','AYWBBBBWYA','.AYNNNNYA.','..ARRRRA..','...OOO....','..OGGGO...','...G.G....'],
    queues: [['green','orange','red'],['blue','cyan','indigo'],['gold','white','yellow']],
    modifiers: combineModifiers(frozen(['3,3','6,3']), shielded(['4,6','5,6'])) }),
];
