import type { LevelDefinition } from '../engine/types';
import {
  combineModifiers, frozen, linked, makeM4CLevel as level, shielded,
  ventRows, ventRowsCapped,
} from './m4cLevelFactory';

export const M4C_WORLD_9: LevelDefinition[] = [
  level({ id: 81, title: 'Starlit Potion', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRows(['...WWW...','...PCP...','..PPPPP..','.PNNNNNP.','PNBBBBBNP','PBCYYYCBP','PBCTTTCBP','.PPGGGPP.','..AAAAA..']),
    queues: [['gold','green','teal'],['yellow','cyan','blue'],['white','purple','indigo']],
    modifiers: linked([['3,0','5,0']]) }),
  level({ id: 82, title: 'Living Spellbook', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRows(['RRRR..BBBB','RWWR..BWWB','RWYR..BCWB','RWAR..BTWB','RWWR..BWWB','RRRRNNBBBB','..NNNNNN..','.PPNNNNPP.','..PP..PP..']),
    queues: [['purple','indigo'],['teal','cyan','blue'],['white','yellow','gold','red']],
    modifiers: linked([['0,0','9,0'],['2,16','7,16']]) }),
  level({ id: 83, title: 'Moon Mage Hat', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRows(['...YYY...','..YYYYY..','...PNP...','..PNNNP..','..NCCCN..','.NCTTCN..','.NNGGGNN.','NNNNNNNNN','.RRRAARRR']),
    queues: [['red','gold'],['green','teal','cyan'],['purple','indigo','yellow']],
    modifiers: combineModifiers(linked([['4,0','4,16']]), frozen(['4,8'])) }),
  level({ id: 84, title: 'Ember Dragon Egg', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRows(['...RRR...','..RDDDR..','.RDOOODR.','RDOYYYODR','RDYWWWYDR','RDWPPPWDR','.RPPPPPR.','..PNNNP..','...AAA...']),
    queues: [['gold','indigo','purple'],['white','yellow'],['orange','coral','red']],
    modifiers: combineModifiers(linked([['3,0','5,0']]), shielded(['4,8'])) }),
  level({ id: 85, title: 'Runebound Sword', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRowsCapped(['...CCC...','..CCCCC..','..CCWCC..','..CCWCC..','..CCYCC..','..CCACC..','..NNRNN..','.NNRRRNN.','NNR...RNN','PP.....PP']),
    queues: [['purple','red'],['indigo','gold'],['yellow','white','cyan']],
    modifiers: linked([['4,0','1,16'],['3,14','5,14']]) }),
  level({ id: 86, title: 'Verdant Crystal Staff', themeId: 'arcane-relics', difficulty: 'medium',
    art: ventRowsCapped(['...LLLL...','..LGGGL..','.LGTTTGL.','..GCCCG..','..CCCBCCC.','..NNNBNNN.','...NWN...','...NYN...','..RRARR..','..RR.RR..']),
    queues: [['red','gold','yellow'],['white','indigo','blue'],['cyan','teal','green','lime']],
    modifiers: combineModifiers(linked([['3,0','6,0']]), frozen(['4,8']), shielded(['4,15'])) }),
  level({ id: 87, title: 'Phoenix Sigil', themeId: 'arcane-relics', difficulty: 'hard',
    art: ventRows(['R...A...R','RR.AAA.RR','.RAYYYAR.','..YOOOY..','.YOWWOY.','..ORRRO..','.PPPRPPP.','PP.NNN.PP','P..CCC..P']),
    queues: [['cyan','indigo','purple'],['white','orange'],['yellow','gold','red']],
    modifiers: combineModifiers(linked([['0,0','8,0'],['0,16','8,16']]), shielded(['4,8'])) }),
  level({ id: 88, title: 'Gilded Griffin', themeId: 'arcane-relics', difficulty: 'hard',
    art: ventRows(['AA..YY..AA','AAA.YY.AAA','.AAYYYYAA.','..YWWWWY..','.YWBBBBWY.','YYBNNNNBYY','YBNRRRRNBY','.BRR..RRB.','GGG....GGG']),
    queues: [['green','red'],['indigo','blue'],['white','yellow','gold']],
    modifiers: combineModifiers(linked([['0,0','9,0'],['0,16','9,16']]), frozen(['4,8','5,8'])) }),
  level({ id: 89, title: 'The Arcane Portal', themeId: 'arcane-relics', difficulty: 'hard',
    art: ventRowsCapped(['...PPPP...','.PNNNNNNP.','PNBBBBBBNP','PNBCCCB BNP'.replace(' ',''),'PNBCTTCBNP','PNBCGCCBNP','PNBBBBBBNP','.PNNNNNNP.','..PPAA PP..'.replace(' ',''),'...ARRA...']),
    queues: [['red','gold','green'],['teal','cyan'],['blue','indigo','purple']],
    modifiers: combineModifiers(linked([['3,0','6,0'],['3,16','6,16']]), frozen(['4,8']), shielded(['5,8'])) }),
  level({ id: 90, title: 'Throne of Relics', themeId: 'arcane-relics', difficulty: 'hard',
    art: ventRowsCapped(['A...AA...A','.AAYYYYAA.','AYYWWWWYYA','AYWPPPPWYA','AYPNNNNPYA','AYPNCCNPYA','AYPNRRNPYA','.APNNNNPA.','..PPBBPP..','..GG..GG..']),
    queues: [['green','blue','red'],['cyan','indigo','purple'],['white','yellow','gold']],
    modifiers: combineModifiers(linked([['0,0','9,0'],['2,16','7,16']]), frozen(['4,6','5,6']), shielded(['4,12','5,12'])) }),
];
