import type { LevelDefinition } from '../engine/types';
import { aerate, linked, makeM4CLevel as level, ventRows } from './m4cLevelFactory';

export const M4C_WORLD_8: LevelDefinition[] = [
  level({ id: 71, title: 'Twin Diving Bell', themeId: 'tidal-depths', difficulty: 'easy',
    tutorial: 'Linked pixels clear together — activate both.',
    art: ventRows(['..AAAAA..','.AWWWWYA.','AWWCCCYYA','AWCBBBCYA','AWCBTBCYA','AWCTTTCYA','.AWWWWYA.','..RRRRR..','...R.R...']),
    queues: [['red','teal'],['blue','cyan'],['white','yellow','gold']],
    modifiers: linked([['2,0','6,0']]) }),
  level({ id: 72, title: 'Azure Manta', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['BB......BB','BBB....BBB','BBBBCCBBBB','.BBCTTCBB.','..CTGGTC..','...TYYT...','...RRRR...','...AAA....']),
    queues: [['gold','red'],['yellow','green','teal'],['cyan','blue']],
    modifiers: linked([['0,0','9,0']]) }),
  level({ id: 73, title: 'Coral Crown', themeId: 'tidal-depths', difficulty: 'medium',
    art: aerate(['D..D.D..D','DD.DDD.DD','DDDDDDDDD','.DDWWWDD.','..WAAAW..','.WATTAW.','WWTBBBTWW','.CCCCCCC.','..GGGGG..']),
    queues: [['green','cyan','blue'],['teal','gold','white'],['coral']],
    modifiers: linked([['0,0','16,0']]) }),
  level({ id: 74, title: 'Pocket Submarine', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['....YYY...','...YWWY...','..NNNNNN..','.NCCCCCCN.','NNCTTTTCNN','NNCGGGGCNN','.NNNNNNNN.','...BBBB...','....Y.....']),
    queues: [['blue','indigo'],['green','teal'],['cyan','white','yellow']],
    modifiers: linked([['4,0','4,16']]) }),
  level({ id: 75, title: 'Lantern Angler', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['......Y..','.....YYY.','....Y.YY.','..BBBBB..','.BNNNNNB.','BNPWWWP NB'.replace(' ',''),'BNPRRRPBN','.BPPPPP B.'.replace(' ',''),'..CCCCC..']),
    queues: [['cyan','purple','red'],['white','indigo'],['blue','yellow']],
    modifiers: linked([['6,0','5,16']]) }),
  level({ id: 76, title: 'Emerald Sea Turtle', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['...GGGG...','..GLLLLG..','.GLTTTTLG.','GLTYYYYTLG','GLYWWWWYLG','.GLCCCCLG.','..GBBBBG..','...G..G...','..BB..BB..']),
    queues: [['blue','cyan'],['white','yellow'],['teal','lime','green']],
    modifiers: linked([['3,0','6,0']]) }),
  level({ id: 77, title: 'Moon Pearl Oyster', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['..PPPPP..','.PBBBBBP.','PBNNNNNBP','PBCWW WCBP'.replace(' ',''),'PBCWYWCBP','.PCTTTC P.'.replace(' ',''),'..PTTTP..','...YYY...']),
    queues: [['teal','yellow'],['white','cyan'],['indigo','blue','purple']],
    modifiers: linked([['2,0','6,0']]) }),
  level({ id: 78, title: 'Crimson Kraken', themeId: 'tidal-depths', difficulty: 'medium',
    art: ventRows(['...RRRR...','..RDDDDR..','.RDDOODDR.','RDDYYYYDDR','RDYWWWWYDR','.RDDOODDR.','..RPPPR...','.RR.P.RR..','RR..B..RR.']),
    queues: [['blue','purple'],['white','yellow','orange'],['coral','red']],
    modifiers: linked([['3,0','6,0'],['0,16','8,16']]) }),
  level({ id: 79, title: 'Sunken Admiral Helm', themeId: 'tidal-depths', difficulty: 'hard',
    art: ventRows(['..YYYYYY..','.YYYYYYYY.','YYWWNNWWYY','YYWNNNNWYY','YYNCCCCNYY','.YNTTTTNY.','..NGGGGN..','..NBBBBN..','.NNNNNNNN.']),
    queues: [['blue','green'],['teal','cyan','indigo'],['white','yellow']],
    modifiers: linked([['2,0','7,0'],['1,16','8,16']]) }),
  level({ id: 80, title: 'The Leviathan Gate', themeId: 'tidal-depths', difficulty: 'hard',
    art: [...ventRows(['C..C..C..C','C..CCCC..C','.CTTTTTTC.','CTGLLLLGT.','.TGLYYLGT.','.TGLYYLGT.','.TGLLLLGT.','CCTBBBBTCC']), 'CC.NNNN.CC', 'N..NNNN..N'],
    queues: [['indigo','blue'],['yellow','lime'],['green','teal','cyan']],
    modifiers: linked([['0,0','9,0'],['0,16','9,16'],['3,4','7,4']]) }),
];
